language:
- python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: OmC0Z68RJGcfDtCyYLuw9uAcTci34zdy8eeLbiBkWXgXBdzZQAncvWiaJ3Ix5RyC9wxGczi76Q2nG4x8x4WjWKNAHiWE99V2c9BRstazHyLO3N0/rWJtgJ9TzLnZ6WvT53OiDci5SHUoz+wCn3N1DLgRt1juOGb80ximCpbzwXO+vYyufkBQDxcGpqaFcGmRbT23KVZNtBCAslKdp76dDtqqfMsWT5Z4LuVGlsiIgWG2loFPDP8+eAx2xcvnZP6Oc6iSmWatsFn9jvyqnmyC2EyxQbaRk3YlRNics56rxC+FmXJPhqHARhzFlHWNJrgm+wm0JorUVhhqR7GYXGUWQoY/rNTN7MTdyrp7VYrocfCxqwuOGDQVxjVPNXxdz5wlKkc5oxO4dYd2KONxZIAFY7ThIszFpdTnepYn3eA7Dbw3WuwpvDCz/ejocwNUexBIwzaY40sWNqRUE9/VTS5Y8JpU/3XqF/3XGp43H5mV1K9640YFUXWMEyzTnUl6siW0kK2eWO9erqc6onbR4mHYOpkRm9S6K2Gfgd98QYZ8vWmgCOzoraRC8FUjqz2Rmid/GpbhZWPlFqkl9Q7/JZWf5qVimZhnfWf3aRgNWwOXD3DLX+BGmgb8Ce0qpRic95Pe05acL6bilA7f8OwOJJscgSprdKZNh7IYyOjzem3tD10=
  app: blooming-garden-73561
  on:
    repo: xanthoc/flasktaskr
