language:
- python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: JyrFHyexC5QjiU7Yxgs+b+WOJryk0Z0NgdqVOE7YNBhNd2dq2dN40BGqHq+VOehyscILVDHwq07zNXblFIkFyQn/lhcN6AXdOo3qXcVyP1wXANtETIw4+huAzWYC+eeTtE8V5K+qPnJO6wFiFPH5Ga/jp2dRFRwtZ/1GxDa7QWMkDz3iGOHG38MuatiyGRYqgoh+BFhzMo2qjSqReoX+czHYD2W6dfbDzcKlzJ+gu6h1+cToEZ8vYCj5d68Cn5aT/XeAZl1Fkx+CAu5Li/vrn/De0rFg8mvWUdcaT7n1FfMZ02SU4aJDpc3B0+4WYNk/Zskg0AOuuUzcDNR67HGVQ034MuorwVw7OBc/eEkmn/+7t3Bxms6VW28TKgbuHUIQsRALAgQb3LSL1IhPJDXv/dzYL6Yx3aOx8E/HhQeTA90xaZGZC0dfitju/+3n+rWnaUdAqr3+D8bLvGmXgnDuhl37E3Enlj4pOOwB0w/pxpBXQNPCBy8QkfJiEAoX+4POU+/snI7Tfjg+DARt+B1yfWPf2p6cs8jhOeUi5Hthp5Xl8X5KnTFCbQ2oTk21Eu4klBsRh/qDwBgZT4pviJwZ0lqye0WtXiqkSdUZZth52FEEfNMo8/uJgQB3rqls7Ke18NvfnRzhgXuSgxCXRHhMoBjZD4rnRzfWDbWFACVvkO4=
  app: flasktaskr
  on:
    repo: xanthoc/flasktaskr
