language:
- python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: oVGE8OYopLIcBDYhqARwjjpK3rXgvw9iI2nS1U+UZ3VLEA8FoCvTRlotYRNer1RpOWPmwlhJcHrbIQhLq7/IBy0eNNpBV85iZQ8LDQGMRx10cTlq7LBd0mL/SnC89Q1YPk9FyMv88xckBuPGpLeFlp9BLl/DcX8UXWbXuQH3IbTAogXIOasU3rVWUQHkNOe25yOyvNeikTYIrucUk9/slmIIzSBVORIuhmn3be76fUSuwsVoHswZqpXUbIak2Mk4ZIg8pvGPEQINUVONbIH8rMoElUrjjRG9GSFD+ItpPC2J7D7yZ6eJ5CJjyiPwFeqZvlMCsILz0YkzWofJXlYuWBzLl6J/l43iEIucmlgDAyGOnA3Zg/qwxoAlCS3/dBkw2N2xtKL+nf1z/ifcbUwJdDMVg82y7snjujRrlq2kA+VjFHRKHaKV6KS3rc491PSUEKGv/FvCIakY/StHSIK6lNgig11WN26nJmmRqBE4MJFahRMbufyZOarei9eiwMuS4VQuRioJ7HLGdHntoHz2bh7FcAUklbi3Azk59H7bM5vd2R6LR2zRQD3SbxR+QZpTK5Uh8rv263f3LVycAvKbSIGU8N1CnS2zfH8jYKevLez5yWW/weF04vnHyjRzlfFlFBoYxIQYTLJaql59E5SkL4LPEP1e20OvV7VKp9mv8wk=
  app: flasktaskr
  on:
    repo: xanthoc/flasktaskr
