language:
- python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: oAMco/y//TLCD31fupsSc8gDkxXzcfFOS9S0tKZoQ/amvcoPLk/BoIiykbuWNkp5nW3x3y+yns1MTQ2GP+DFFyp5IHQKWqAXt2NXcqhlBnvnk36xkXDkBBXfCNEJ7/gmbAvLCOIPrAwYyIGmX5+CGqrtBBAeDobfTSvCSktrr6LOi0VUXWQ6F8eRb6dsyhBR6Cpt++Gh5BKDle+UnEH+gdnxswzZq8YslxIZZ1Vf0QU4W7T8kcItk5qBxp5kgWteVs/v/CGzqBUse1DdjBKoc7SDOGML0wyJ3LDhGt1/kSyANnjmp5ydJWBlJwiZoeA0AWnlpjUy3bP/8/huUDPfPmRG5CjiTOMdDvSmkppxqToDBIWOyO5lUmLX51dXk3FpYME60+ucicb5lTSauECPE281meKGyMZ58F1pRMU9lgzskqQyXdirUtpfs+Qrd5SwOa4NRtrMM9ObZvuF/NbK7k6B+Tx1N3D5cxjDmn70nQWaFmh4f0wpNu+9kPi81WZA7f07t77lSZy+LGcYApeQKx8a5ba29VosLgU49XtpQHAhA/jsr6nPVCAGDs39ghzCm7xhaLJIhPxq2HeHxZ1WORiPf22L+lsFILuOsK2DrDb7FvrIA/lw0W+cdI+JuEifQYI4G04Xqk1DTXc/Kl3CLv+ygHjAjneLJ8vmczBupu8=
  app: flasktaskr
  on:
    repo: xanthoc/flasktaskr
